### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Olympic1** [KSatNet/RATPack#1]
You must include the **name** of the license somewhere in the file
- Creative Commons
- MIT
- WTFPL
- BSD
- GPL

**Comment by KSatNet** [comment]
It is a definition of the terms for using this mod, and does not conform to any existing license. I was not happy with the terms of other licenses, so I wrote my own. I shall dub it the "SatNet Mod License".

**Comment by Olympic1** [comment]
ok, thanks for that
